export const movies = 'https://api.themoviedb.org/3/movie/'
export const tv = 'https://api.themoviedb.org/3/tv/'
export const keyapi = 'api_key=20faa502b37d1952b65968e92b756db7'
export const image = 'https://image.tmdb.org/t/p/w200'
export const imageLarge = 'https://image.tmdb.org/t/p/w300'
export const searchUrl = 'https://api.themoviedb.org/3/search/movie/'
export const searchUrlTv = 'https://api.themoviedb.org/3/search/tv/'